language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
    - php: 7.0
  fast_finish: true

before_install: composer self-update

install: composer install -n

script:
  - vendor/bin/phpunit -v --exclude-group functional --coverage-clover=coverage.xml

after_script:
  - sh -c 'if [ $(phpenv version-name) = "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

after_success:
  - bash <(curl -s https://codecov.io/bash)
