services:
    phlexible_teaser.teaser_hasher:
        class: Phlexible\Bundle\TeaserBundle\Teaser\TeaserHasher
        arguments:
            - "@phlexible_element.element_hasher"

    phlexible_teaser.access_control_provider:
        class: Phlexible\Bundle\TeaserBundle\AccessControl\TeaserPermissionProvider
        tags:
            - {name: phlexible_access_control.permission}

    # event listeners
    phlexible_teaser.listener.apply_successor:
        class: Phlexible\Bundle\TeaserBundle\EventListener\ApplySuccessorListener
        arguments:
            - "@doctrine.dbal.default_connection"
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_teaser.listener.tree:
        class: Phlexible\Bundle\TeaserBundle\EventListener\TreeListener
        arguments:
            - "@phlexible_teaser.teaser_manager"
        tags:
            - {name: kernel.event_subscriber}

    # role providers
    phlexible_teaser.role_provider:
        class: Phlexible\Bundle\TeaserBundle\RoleProvider\TeaserRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

    # twig extensions
    phlexible_teaser.twig.teaser_extension:
        class: Phlexible\Bundle\TeaserBundle\Twig\Extension\TeaserExtension
        arguments:
            - "@fragment.handler"
            - "@router"
            - "@request_stack"
        tags:
            - {name: twig.extension}
