services:
    phlexible_media_tool.exiftool:
        class: PHPExiftool\Reader
        factory: [PHPExiftool\Reader, create]
        arguments:
            - "@logger"
        tags:
            - {name: monolog.logger, channel: media_tools}
