services:
    phlexible_media_tool.ffprobe:
        class: FFMpeg\FFProbe
        factory: [FFMpeg\FFProbe, create]
        arguments:
            - "%phlexible_media_tool.ffmpeg.configuration%"
            - "@logger"
        tags:
            - {name: monolog.logger, channel: media_tools}

    phlexible_media_tool.ffmpeg:
        class: FFMpeg\FFMpeg
        factory: [FFMpeg\FFMpeg, create]
        arguments:
            - "%phlexible_media_tool.ffmpeg.configuration%"
            - "@logger"
            - "@phlexible_media_tool.ffprobe"
        tags:
            - {name: monolog.logger, channel: media_tools}
